const fs = require('fs');
const path = require('path');
const vm = require('vm');

const root = path.resolve(__dirname, '..');
const sourcePath = path.join(root, 'src', 'app.jsx');
const babelPath = path.join(root, 'assets', 'vendor', 'babel.min.js');
const outputPath = path.join(root, 'assets', 'app.js');

const babelCode = fs.readFileSync(babelPath, 'utf8');
const sandbox = { console };
sandbox.window = sandbox;
sandbox.self = sandbox;
sandbox.globalThis = sandbox;
vm.createContext(sandbox);
vm.runInContext(babelCode, sandbox, { filename: babelPath });

const source = fs.readFileSync(sourcePath, 'utf8');
const result = sandbox.Babel.transform(source, {
    presets: [['react', { runtime: 'classic' }]],
    comments: false,
    compact: false,
});

fs.writeFileSync(
    outputPath,
    `/* Generated by scripts/build-app.js. Edit src/app.jsx. */\n${result.code}\n`,
    'utf8'
);

console.log(`Built ${path.relative(root, outputPath)}`);
