const fs = require('fs');
const path = require('path');
const vm = require('vm');
const { loadProjectConfig } = require('./lib/project-config');

const root = path.resolve(__dirname, '..');
const sourceRoot = path.join(root, 'src');
const sourceManifestPath = path.join(sourceRoot, 'app.sources.json');
const babelPath = path.join(root, '.github', 'vendor', 'babel.min.js');
const outputPath = path.join(root, 'assets', 'app.js');
const projectConfig = loadProjectConfig(root);

const babelCode = fs.readFileSync(babelPath, 'utf8');
const sandbox = { console };
sandbox.window = sandbox;
sandbox.self = sandbox;
sandbox.globalThis = sandbox;
vm.createContext(sandbox);
vm.runInContext(babelCode, sandbox, { filename: babelPath });

const sourceManifest = JSON.parse(fs.readFileSync(sourceManifestPath, 'utf8'));
if (!Array.isArray(sourceManifest) || !sourceManifest.length) {
    throw new Error('src/app.sources.json must contain at least one source file.');
}

const sourceFiles = sourceManifest.map(relativePath => {
    if (typeof relativePath !== 'string' || !relativePath.trim()) {
        throw new Error('Every app source path must be a non-empty string.');
    }
    const absolutePath = path.resolve(root, relativePath);
    const pathWithinSourceRoot = path.relative(sourceRoot, absolutePath);
    if (pathWithinSourceRoot.startsWith('..') || path.isAbsolute(pathWithinSourceRoot)) {
        throw new Error(`App source must stay inside src/: ${relativePath}`);
    }
    if (!fs.existsSync(absolutePath)) {
        throw new Error(`Missing app source: ${relativePath}`);
    }
    return { relativePath, absolutePath };
});

const source = [
    `const PROJECT_CONFIG = Object.freeze(${JSON.stringify(projectConfig)});`,
    ...sourceFiles
    .map(({ relativePath, absolutePath }) =>
        `/* Source: ${relativePath} */\n${fs.readFileSync(absolutePath, 'utf8')}`
    ),
].join('\n\n');
const result = sandbox.Babel.transform(source, {
    presets: [['react', { runtime: 'classic' }]],
    comments: false,
    compact: false,
});

fs.writeFileSync(
    outputPath,
    `/* Generated by scripts/build-app.js from src/app.sources.json. */\n${result.code}\n`,
    'utf8'
);

console.log(`Built ${path.relative(root, outputPath)} from ${sourceFiles.length} source files`);
